media:
  - name: images
    label: Images
    input: src/assets/images
    output: /images
    extensions:
      - apng
      - avif
      - gif
      - jpeg
      - jpg
      - png
      - svg
      - webp
content:
  - name: global
    label: Global
    type: file
    path: content/global.yaml
    fields:
      - name: navItemRegister
        label: Nav Item Register
        description: Register text in primary navigation.
        type: text
        required: true
      - name: navItemSeminars
        label: Nav Item Seminars
        description: Seminars text in primary navigation.
        type: text
        required: true
      - name: navItemInfo
        label: Nav Item Info
        description: Info text in primary navigation.
        type: text
        required: true
      - name: navItemAbout
        label: Nav Item About
        description: About text in primary navigation.
        type: text
        required: true
      - name: navItemContact
        label: Nav Item Contact
        description: Contact text in primary navigation.
        type: text
        required: true
      - name: navItemImprint
        label: Nav Item Imprint
        description: Imprint text in secondary navigation.
        type: text
        required: true
      - name: navItemPrivacy
        label: Nav Item Privacy
        description: Privacy text in secondary navigation.
        type: text
        required: true
      - name: navItemTerms
        label: Nav Item Terms
        description: Terms text in secondary navigation.
        type: text
        required: true
  - name: seminars
    label: Seminars
    type: collection
    path: content/seminars
    fields:
      - name: mainTitle
        label: Main Title
        description: Seminar main title.
        type: text
        required: true
      - name: additionalTitle
        label: Additional Title
        description: Seminar additional title as a smooth continuation of the main title.
        type: text
      - name: teacher
        label: Teacher
        description: Seminar teacher.
        type: reference
        required: true
        options:
          collection: teachers
          value: "{name}"
      - name: body
        label: Description
        description: Seminar description.
        type: rich-text-full
        required: true
      - name: weight
        label: Sorting weight
        description: Weight determining the item's position in the list.
        type: number
    filename: "{primary}.md"
    view:
      fields:
        - mainTitle
        - additionalTitle
        - weight
      default:
        sort: weight
        order: desc
  - name: teachers
    label: Teachers
    type: collection
    path: content/teachers
    fields:
      - name: name
        label: Name
        description: Teacher name.
        type: text
        required: true
      - name: image
        label: Image
        description: Teacher image in original dimensions with a minimum size of TODOpx.
        type: image
        required: true
        options:
          media: images
      - name: headline
        label: Headline
        description: Teacher headline.
        type: text
        required: true
      - name: description
        label: Description
        description: Teacher description.
        type: rich-text-full
        required: true
        options:
          media: false
      - name: videos
        label: Videos
        description: Teacher YouTube videos.
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - name: title
            label: Title
            description: Video title.
            type: text
            required: true
          - name: id
            label: YouTube URL
            description: YouTube video URL (www.youtube.com/watch?v=... or youtu.be/...).
            type: text
            required: true
    filename: "{primary}.yaml"
    format: yaml
  - name: info_main_coll
    label: Info - Main - Collection
    type: collection
    path: content/info_main_coll
    fields:
      - name: title
        label: Title
        description: Title (heading) for the information or FAQ question.
        type: text
        required: true
      - name: body
        label: Information
        description: Information body or FAQ answer.
        type: rich-text-full
        required: true
      - name: weight
        label: Sorting weight
        description: Weight determining the item's position in the list.
        type: number
    filename: "{primary}.md"
  - name: info_location_coll
    label: Info - Location - Collection
    type: collection
    path: content/info_location_coll
    fields:
      - name: title
        label: Title
        description: Title (heading) for the information or FAQ question.
        type: text
        required: true
      - name: body
        label: Information
        description: Information body or FAQ answer.
        type: rich-text-full
        required: true
      - name: weight
        label: Sorting weight
        description: Weight determining the item's position in the list.
        type: number
    filename: "{primary}.md"
  - name: info_faq_coll
    label: Info - FAQ - Collection
    type: collection
    path: content/info_faq_coll
    fields:
      - name: title
        label: Title
        description: Title (heading) for the information or FAQ question.
        type: text
        required: true
      - name: body
        label: Information
        description: Information body or FAQ answer.
        type: rich-text-full
        required: true
      - name: weight
        label: Sorting weight
        description: Weight determining the item's position in the list.
        type: number
    filename: "{primary}.md"
  - name: about
    label: About
    type: file
    path: content/about.md
    fields:
      - name: title
        label: Title
        description: About title.
        type: text
        required: true
      - name: body
        label: Body
        description: About body.
        type: rich-text-full
        required: true
        options:
          media: images
  - name: imprint
    label: Imprint
    type: file
    path: content/imprint.md
    fields:
      - name: title
        label: Title
        description: Imprint title.
        type: text
        required: true
      - name: body
        label: Body
        description: Imprint body.
        type: rich-text-full
        required: true
        options:
          media: images
  - name: privacy
    label: Privacy
    type: file
    path: content/privacy.md
    fields:
      - name: title
        label: Title
        description: Privacy policy title.
        type: text
        required: true
      - name: body
        label: Body
        description: Privacy policy body.
        type: rich-text-full
        required: true
        options:
          media: images
  - name: terms
    label: Terms
    type: file
    path: content/terms.md
    fields:
      - name: title
        label: Title
        description: Terms and conditions title.
        type: text
        required: true
      - name: body
        label: Body
        description: Terms and conditions body.
        type: rich-text-full
        required: true
        options:
          media: images
  - name: footer
    label: Footer
    type: file
    path: content/footer.yaml
    fields:
      - name: facebookUrl
        label: Facebook URL
        description: Facebook page URL. If it is empty, the icon will not be displayed.
        type: text
      - name: instagramUrl
        label: Instagram URL
        description: Instagram page URL. If it is empty, the icon will not be displayed.
        type: text
      - name: youtubeUrl
        label: YouTube URL
        description: YouTube page URL. If it is empty, the icon will not be displayed.
        type: text
      - name: githubUrl
        label: GitHub URL
        description: GitHub page URL. If it is empty, the icon will not be displayed.
        type: text
      - name: partners
        label: Partners
        description: List of partners.
        type: object
        list:
          collapsible:
            collapsed: true
            summary: "{fields.title}"
        fields:
          - name: title
            label: Title
            description: Partner name.
            type: text
            required: true
          - name: url
            label: URL
            description: Partner URL
            type: text
            required: true
          - name: image
            label: Image
            description: Partner logo in original dimensions with a minimum size of 192x72px.
            type: image
            required: true
            options:
              media: images
settings:
  hide: true
