media:
  - name: images
    label: Images
    input: src/assets/images
    output: /images
    extensions:
      - apng
      - avif
      - gif
      - jpeg
      - jpg
      - png
      - svg
      - webp
content:
- name: Teachers
  label: Teachers
  type: collection
  path: content/teachers
  fields:
  - name: name
    label: Name
    description: Teacher name.
    type: text
    required: true
  - name: headline
    label: Headline
    description: Teacher headline.
    type: text
    required: true
  - name: description
    label: Description
    description: Teacher description.
    type: rich-text-full
    required: true
    options:
      media: images
settings:
  hide: true
