media:
  - name: images
    label: Images
    input: src/assets/images
    output: /images
    extensions:
      - apng
      - avif
      - gif
      - jpeg
      - jpg
      - png
      - svg
      - webp
content:
- name: Teachers
  label: Teachers
  type: collection
  path: content/teachers
  fields:
  - name: name
    label: Name
    description: Teacher name.
    type: text
    required: true
  - name: image
    label: Image
    description: Teacher image in original dimensions with a minimum size of TODOpx.
    type: image
    required: true
    options:
      media: images
  - name: headline
    label: Headline
    description: Teacher headline.
    type: text
    required: true
  - name: description
    label: Description
    description: Teacher description.
    type: rich-text-full
    required: true
    options:
      media: false
  - name: videos
    label: Videos
    description: Teacher YouTube videos.
    type: object
    list:
      collapsible:
        collapsed: true
        summary: "{fields.title}"
    fields:
    - name: title
      label: Title
      description: Video title.
      type: text
      required: true
    - name: id
      label: ID
      description: YouTube video ID.
      type: text
      required: true
settings:
  hide: true
